### ISSUE TITLE
Error in as.data.frame.default(x[[i]], optional = TRUE) :    cannot coerce class ""eigenvals"" to a data.frame

### ISSUE THREAD

**Issue by hanlunliu** [PoisotLab/paco#28]
Hi there, 
Does anyone know why this error occurs in function "add_pcoord"?

Error in as.data.frame.default(x[[i]], optional = TRUE) :    cannot coerce class ""eigenvals"" to a

 data.frame

Here is my code:
`pdist <- cophenetic(ptree)

 adist <- cophenetic(atree)

  D <- prepare_paco_data(pdist, adist, as.matrix(web))

  D <- add_pcoord(D)

  Dlist <- PACo(D, nperm=1000, seed=1, method="swap",shuffled = T)`

But it stuck in the add_pcoord step, I have 100 bipartite networks but only 3 encountered this error, I put one of them and its corresponding phylogenetic trees in the attachment.    
[example.zip](https://github.com/PoisotLab/paco/files/2570421/example.zip)

**Comment by matthutchinson1** [comment]
Hi hanlunliu,

We are working on this issue and will get back to you soon.

Best,
- Matt

**Comment by hanlunliu** [comment]
Hi Matt,

Thanks a lot! I am looking forward to your reply.

Best,
Hanlun

________________________________
发件人: matthutchinson1 <notifications@github.com>
发送时间: Friday, November 16, 2018 10:39:00 PM
收件人: PoisotLab/paco
抄送: hanlunliu; Author
主题: Re: [PoisotLab/paco] Error in as.data.frame.default(x[[i]], optional = TRUE) : cannot coerce class ""eigenvals"" to a data.frame (#28)


Hi hanlunliu,

We are working on this issue and will get back to you soon.

Best,

  *   Matt

―

**Comment by Biogeographer** [comment]
I am also receiving this error for all my datasets with paco v0.3.2 as of today.

**Comment by Biogeographer** [comment]
I will add that, if I do my own PCoAs on my data and add them to the list of D, the problem that arises in the PACo function is that the matrices don't have the same number of rows, so I would have to do that part of the transformation myself in order to run procrustes directly from vegan.

**Comment by Biogeographer** [comment]
I found a work around for this by simply transforming the offending matrix by taking its square root. Presumably this prevented the negative eigenvalues that were probably throwing the error. Here's my code:

`D = prepare_paco_data(adist, bdist, ab_links)`
`#adist is my host distance matrix and bdist is my parasite distance matrix; ab_links is my association matrix`
`D = add_pcoord(D)`
`#This threw the error described above.`
`#The next two lines utilize the paco object created in the first line of code but perform principle coordinates on the matrices within the object using the pcoa function from the ape library. This is in contrast to using the modified version of pcoa internal to add_pcoord(). Presumably, one or both matrices in the paco object will throw the error described above and, therefore, let you know which you need to transform.`
`H_PCo = pcoa(D$H, correction="lingoes")$vectors`
`P_PCo = pcoa(D$P, correction="lingoes")$vectors`
`#In my case, P_PCo, my parasite matrix, threw the error.  So...`
`bdist.sqrt = sqrt(bdist)`
`D = prepare_paco_data(adist, bdist.sqrt, ab_links)`
`D = add_pcoord(D)`
`D = PACo(D) #with options`

Hope this helps others!

Just FYI: You can read up elsewhere online about transforming matrices that throw negative eigenvalues using the square root.

**Comment by matthutchinson1** [comment]
Hi Hanlun, 

I am looking into this again but when I try to use your example data it just has one phylogeny in it. Can you please add the interaction matrix and the other phylogeny?

Best,
- Matt

**Comment by hanlunliu** [comment]
> Hi Hanlun,
> 
> I am looking into this again but when I try to use your example data it just has one phylogeny in it. Can you please add the interaction matrix and the other phylogeny?
> 
> Best,
> 
> * Matt

Hi Matt,

I exported the interaction matrix and two corresponding phylogenies to three separate files, please try again. The file "atree" corresponds to columns of the matrix, and "ptree" to the rows. 

Best,

Hanlun 

[example.zip](https://github.com/PoisotLab/paco/files/3144009/example.zip)

**Comment by matthutchinson1** [comment]
Hi Hanlun,

Thanks so much for that. I have identified the issue and we will be issuing a new version of the R package in the next week. As the error message suggested, there is an issue within the function of data being in the wrong class. My apologies that it has taken this long to get to the root of this issue. 

Please watch out for the new version.

Best,
- Matt

**Comment by hanlunliu** [comment]
Hi Matt,

Thank you very much for solving the problem. I am looking forward to the new version.

Best,

Hanlun


________________________________
发件人: matthutchinson1 <notifications@github.com>
发送时间: Wednesday, May 8, 2019 12:55:58 AM
收件人: PoisotLab/paco
抄送: hanlunliu; Author
主题: Re: [PoisotLab/paco] Error in as.data.frame.default(x[[i]], optional = TRUE) : cannot coerce class ""eigenvals"" to a data.frame (#28)


Hi Hanlun,

Thanks so much for that. I have identified the issue and we will be issuing a new version of the R package in the next week. As the error message suggested, there is an issue within the function of data being in the wrong class. My apologies that it has taken this long to get to the root of this issue.

Please watch out for the new version.

Best,

  *   Matt

―
