### ISSUE TITLE
Move modified `coordpcoa` to it's own non-exported function

### ISSUE THREAD

**Issue by efcaguab** [PoisotLab/paco#4]
The function `coordpcoa` in add_pcoord.r is a version of of `ape::pcoa` modified by @matthutchinson1. It probably should be in it's own non-exported function within the package and comment it to clarify that it has been borrowed from ape

**Comment by matthutchinson1** [comment]
Okay no problem, how do I do that?

**Comment by tpoisot** [comment]
Good point!

@matthutchinson1, I think it's just a matter of (i) removing the @export directive, and (ii) adding a line about the function being adapted from ape in the documentation.

**Comment by matthutchinson1** [comment]
Hi guys,

I just tried to call add_pcoord.r in R and it failed to find it. Is this because the @export directive has been removed?

**Comment by efcaguab** [comment]
Yes it's because of that. In my opinion in an ideal situation the modified function would be in its own r file without the export directive. In that way the function can be called without problem from inside paco but it's not directly accessible from outside the package.
- Fer

**Comment by efcaguab** [comment]
Though maybe the easiest at this point is to just leave `coordpcoa` where it is and put back the `@export`. The note you put in the documentation should be sufficient.

**Comment by matthutchinson1** [comment]
I'm happy with whatever- I can easily split the two functions into separate files. What do you think @tpoisot?

**Comment by tpoisot** [comment]
Even if not exported, you can always use it with `paco:::coordpcoa` -- if it's going to be used by package users a lot, it might be exported. If not, I have no issues with it being hidden.

**Comment by matthutchinson1** [comment]
At this point I have hidden it, but as you said it can always be changed. Docs should be updated too :)
