### ISSUE TITLE
Properly naming procrustes residuals

### ISSUE THREAD

**Issue by efcaguab** [PoisotLab/paco#8]
So right now we are looking into having a deeper look at the procrustes residuals directly. Of course you can always call `vegan::residuals (D$proc)`, but you get uninformative names (the name of the host of each interaction). Also, one can look at the raw residual matrix it's possible by running `D$proc$X - D$proc$Yrot`, but again the names are uninformative. 

I wrote the function `residuals_paco` in 24ac0801726886ab9966f83aba30e0c22b106fc6 which returns the ss residuals for each interaction or the raw residual matrix of a paco object with informative names. However I'm not sure that's the best way to go around it. 

Another, more elegant solution is to use to our advantage the fact that `residuals` is a generic in R. That requires stopping treating D as a normal list and start treating it as a S3 class (which I think would be a good idea as well). 

Instead of defining the new function as `residuals_paco` we name it `residuals.paco`. That way running `residuals (D)` will suffice as R will figure out we are trying to use the method on an object of `paco` class.

What do you guys think?

**Comment by tpoisot** [comment]
Wouldn't the change in `D` break the whole oackage API?

Before we do that (it seems to be a major change), we might have to develop a good test suite.

But in principle, yes, I fully agree. If you manage to pull that off without breaking anything, all the better :grinning:

**Comment by efcaguab** [comment]
Sweet. I think there shouldn't be any issue. After all the class is just stored as an object's attribute, everything else should work pretty much the same way. I'll implement it, do some tests and let you know

**Comment by tpoisot** [comment]
Sounds good, and is obviously the right move.

If you have some tests (and using the examples in the doc would be a first step), I'll set them up using TravisCI and Coveralls, so we will have more confidence when merging things.
